CREATE TABLE "GCG_5644_PL_LOC" (
 "PRODUCT_LINE" CHAR(2) NOT NULL,
 "LOCATION" CHAR(2) );
ALTER TABLE "GCG_5644_PL_LOC" IN DICTIONARY ADD CONSTRAINT "PK_PRODUCT_LINE" PRIMARY KEY  ( "PRODUCT_LINE" ) USING 0;